### ISSUE TITLE
Upgrade Cats dependency to 0.7

### ISSUE THREAD

**Issue by alexandru** [monixio/monix#212]
Cats 0.7 is out and dependency should be upgraded.

**Comment by lukestephenson** [comment]
Note that monix 2.0-RC11 did not work with cats 0.7.  There are breaking changes.

```
[error] (run-main-0) java.lang.AbstractMethodError: monix.cats.EvaluableInstances$$anon$1.tailRecM(Ljava/lang/Object;Lscala/Function1;)Ljava/lang/Object;
java.lang.AbstractMethodError: monix.cats.EvaluableInstances$$anon$1.tailRecM(Ljava/lang/Object;Lscala/Function1;)Ljava/lang/Object;
	at cats.free.Free.foldMap(Free.scala:131)
	at cats.free.Free.foldMapUnsafe(Free.scala:142)
	at demo.AppInterpreter.run(AppInterpreter.scala:12)
	at app.Main$$anonfun$main$1.apply$mcV$sp(Main.scala:20)
	at app.Main$.timed(Main.scala:26)
	at app.Main$.main(Main.scala:17)
	at app.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

In my example, I was using 
```
script.foldMapUnsafe(xxx)
```
so I was surprised to see cats trying to call `tailRecM` on the monix cats Monad.  Could be a bug in cats.

**Comment by lukestephenson** [comment]
I'm now getting some failures.  To resolve this I'm looking to supply custom equality methods for the checking (it's comparing two `Task[Task[Int]]` and only executing the outer task.
```
[info] - CoflatMap[Task[Int]].coflatMap.coflatten throughMap *** FAILED ***
[info]   Falsified after 0 passed tests. (Checkers.scala:36)
[info]   > Labels of failing property:
[info]   (Suspend(<function0>) ?== BindSuspend(<function0>,<function1>)) failed
[info]   > ARG_0: Suspend(<function0>)
[info]     minitest.laws.Checkers$class.check(Checkers.scala:36)
[info]     monix.cats.TaskLawsSuite$.check(TaskLawsSuite.scala:26)
```

**Comment by alexandru** [comment]
Unfortunately I'm blocked by this issue in Cats. ATM `FlatMap` / `Monad` instances are no longer implementable for `Observable` because of `tailRecM`: https://github.com/typelevel/cats/issues/1329

**Comment by alexandru** [comment]
OK, I managed to reconfigure ScalaCheck, such that the tailRecM tests pass for Observable. I'm using the following parameters:

```scala
    Parameters.default
      .withMinSuccessfulTests(10)
      .withMaxDiscardRatio(50.0f)
      .withMaxSize(6)
```

Not good though, because it weakens the tests. I hope Cats will provide a solution for monads that do not want to implement `tailRecM` in the future.

**Comment by alexandru** [comment]
Deployed in `2.0-RC13`
